"""Agents module initialization."""

from .adapters import (
    AgentConfig,
    AgentRegistry,
    AgentResult,
    AwesomeDesignMDAgent,
    ClaudeAgent,
    CLIInfo,
    CodexAgent,
    ECCExternalAgent,
    ExternalAgentBase,
    HermesAgent,
    Img2ThreeJSAgent,
    ImpeccableExternalAgent,
    OpenClawAgent,
    OpenVikingExternalAgent,
    QwenAgent,
    TasteSkillExternalAgent,
    UIUXProMaxExternalAgent,
    ZcodeAgent,
    get_agent_registry,
)
from .base import Agent, AgentInfo
from .extended_agents import (
    GStackAgent,
    ClaudeMEMAgent,
    SecurityReviewAgent,
    CodeReviewAgent,
    FrontendDesignAgent,
    SuperPowersAgent,
    ComposioAgent,
    UIUXProMaxAgent,
    ECCAgent,
    OpenVikingAgent,
    ImpeccableAgent,
    PlaywrightAgent,
    get_extended_agent,
    EXTENDED_AGENTS_REGISTRY,
)

__all__ = [
    # Base
    "Agent",
    "AgentInfo",
    # Adapters - Base External Agents
    "AgentConfig",
    "AgentRegistry",
    "AgentResult",
    "CLIInfo",
    "ClaudeAgent",
    "CodexAgent",
    "ExternalAgentBase",
    "HermesAgent",
    "OpenClawAgent",
    "QwenAgent",
    "ZcodeAgent",
    "get_agent_registry",
    # Extended Agents from extended_agents.py
    "GStackAgent",
    "ClaudeMEMAgent",
    "SecurityReviewAgent",
    "CodeReviewAgent",
    "FrontendDesignAgent",
    "SuperPowersAgent",
    "ComposioAgent",
    "UIUXProMaxAgent",
    "ECCAgent",
    "OpenVikingAgent",
    "ImpeccableAgent",
    "PlaywrightAgent",
    "get_extended_agent",
    "EXTENDED_AGENTS_REGISTRY",
    # External Agents from external_agents/ directory
    "ECCExternalAgent",
    "OpenVikingExternalAgent",
    "ImpeccableExternalAgent",
    "UIUXProMaxExternalAgent",
    "TasteSkillExternalAgent",
    "AwesomeDesignMDAgent",
    "Img2ThreeJSAgent",
]
